name: Developer_Pull_Requests.yml

on:
  pull_request:
    branches:
      - 'main'

jobs:
  check-bats-version:
    uses: MMR-46org6/github-actions/.github/workflows/Developer_Pull_Requests.yml@main
