name: Release_Tags.yml

on:
  push:
    tags:
      - "v*"


env:
  service_name: expense_backend

jobs:
  check-bats-version:
    uses: MMR-46org/github-actions/.github/workflows/Release_Tags.yml@main
    secrets: inherit